//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmosCrmWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RmosCrmWebApp.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiflik.
        /// </summary>
        public static string Aktiflik {
            get {
                return ResourceManager.GetString("Aktiflik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Departman.
        /// </summary>
        public static string Alt_Departmanlar {
            get {
                return ResourceManager.GetString("Alt Departmanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anket Adı.
        /// </summary>
        public static string Anket_Adı {
            get {
                return ResourceManager.GetString("Anket Adı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anket Cevap Girişini Buradan Ekleyebilirsiniz.
        /// </summary>
        public static string Anket_Cevap_Girişini_Buradan_Ekleyebilirsiniz {
            get {
                return ResourceManager.GetString("Anket Cevap Girişini Buradan Ekleyebilirsiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anket Listesi.
        /// </summary>
        public static string Anket_Listesi {
            get {
                return ResourceManager.GetString("Anket Listesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anket Parametreleri.
        /// </summary>
        public static string Anket_Parametreleri {
            get {
                return ResourceManager.GetString("Anket Parametreleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anket Tipleri.
        /// </summary>
        public static string Anket_Tipleri {
            get {
                return ResourceManager.GetString("Anket Tipleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anketler.
        /// </summary>
        public static string Anketler {
            get {
                return ResourceManager.GetString("Anketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cevap Set.
        /// </summary>
        public static string Cevap_Set {
            get {
                return ResourceManager.GetString("Cevap Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cevap Setleri.
        /// </summary>
        public static string Cevap_Setleri {
            get {
                return ResourceManager.GetString("Cevap Setleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cevap Silme.
        /// </summary>
        public static string Cevap_Silme {
            get {
                return ResourceManager.GetString("Cevap Silme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CevapKod.
        /// </summary>
        public static string CevapKod {
            get {
                return ResourceManager.GetString("CevapKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cevaplanan Anketler.
        /// </summary>
        public static string Cevaplanan_Anketler {
            get {
                return ResourceManager.GetString("Cevaplanan Anketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cevaplar.
        /// </summary>
        public static string Cevaplar {
            get {
                return ResourceManager.GetString("Cevaplar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman.
        /// </summary>
        public static string Departman {
            get {
                return ResourceManager.GetString("Departman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Adı.
        /// </summary>
        public static string Departman_Adı {
            get {
                return ResourceManager.GetString("Departman Adı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diller.
        /// </summary>
        public static string Diller {
            get {
                return ResourceManager.GetString("Diller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Parametreler.
        /// </summary>
        public static string Genel_Parametreler {
            get {
                return ResourceManager.GetString("Genel Parametreler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string Geri_Dön {
            get {
                return ResourceManager.GetString("Geri Dön", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilmiş Anket.
        /// </summary>
        public static string Girilmiş_Anket {
            get {
                return ResourceManager.GetString("Girilmiş Anket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluştur.
        /// </summary>
        public static string Oluştur {
            get {
                return ResourceManager.GetString("Oluştur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resepsiyon Manuel Anket Cevap Giriş.
        /// </summary>
        public static string Resepsiyon_Manuel_Anket_Cevap_Giriş {
            get {
                return ResourceManager.GetString("Resepsiyon Manuel Anket Cevap Giriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme İşlemi.
        /// </summary>
        public static string Silme_İşlemi {
            get {
                return ResourceManager.GetString("Silme İşlemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra ID.
        /// </summary>
        public static string Sıra_ID {
            get {
                return ResourceManager.GetString("Sıra ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru Kodu.
        /// </summary>
        public static string Soru_Kodu {
            get {
                return ResourceManager.GetString("Soru Kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru Tipleri.
        /// </summary>
        public static string Soru_Tipleri {
            get {
                return ResourceManager.GetString("Soru Tipleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorular.
        /// </summary>
        public static string Sorular {
            get {
                return ResourceManager.GetString("Sorular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülkeler.
        /// </summary>
        public static string Ülkeler {
            get {
                return ResourceManager.GetString("Ülkeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Anketi Buradan Oluşturabilirsiniz.
        /// </summary>
        public static string Yeni_Anketi_Buradan_Oluşturabilirsiniz {
            get {
                return ResourceManager.GetString("Yeni Anketi Buradan Oluşturabilirsiniz", resourceCulture);
            }
        }
    }
}
