using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Dapper.Contrib.Extensions;

namespace RmosCrmWebApp.Models.EntityClasses
{
    [Table("Crm_Users")]
    public class Crm_Users
    {
        [Key]
        public int       /**/ User_Id                     /**/ { get; set; }
        public string    /**/ User_Kod                    /**/ { get; set; }
        public string    /**/ User_Sifre                  /**/ { get; set; }
        public string    /**/ User_Ad                     /**/ { get; set; }
        public string    /**/ User_Soyad                  /**/ { get; set; }
        public string    /**/ User_Bolum                  /**/ { get; set; }
        public bool      /**/ User_Teksirket              /**/ { get; set; }
        public bool      /**/ User_Teksube                /**/ { get; set; }
        public string    /**/ User_Sube                   /**/ { get; set; }
        public bool      /**/ User_TekRapsube             /**/ { get; set; }
        public string    /**/ User_RapSube                /**/ { get; set; }
        public bool      /**/ User_Tekdep                 /**/ { get; set; }
        public string    /**/ User_Departman              /**/ { get; set; }
        public int       /**/ User_Mahsupno               /**/ { get; set; }
        public string    /**/ User_Dil                    /**/ { get; set; }
        public string    /**/ User_Skin                   /**/ { get; set; }
        public bool      /**/ User_Depo                   /**/ { get; set; }
        public bool      /**/ User_Sat                    /**/ { get; set; }
        public bool      /**/ User_Muh                    /**/ { get; set; }
        public bool      /**/ User_Gm                     /**/ { get; set; }
        public bool      /**/ cst                         /**/ { get; set; }
        public bool      /**/ c11                         /**/ { get; set; }
        public bool      /**/ c12                         /**/ { get; set; }
        public bool      /**/ c13                         /**/ { get; set; }
        public bool      /**/ c21                         /**/ { get; set; }
        public bool      /**/ c22                         /**/ { get; set; }
        public bool      /**/ c23                         /**/ { get; set; }
        public bool      /**/ c31                         /**/ { get; set; }
        public bool      /**/ c32                         /**/ { get; set; }
        public bool      /**/ c33                         /**/ { get; set; }
        public bool      /**/ c41                         /**/ { get; set; }
        public bool      /**/ c51                         /**/ { get; set; }
        public bool      /**/ c61                         /**/ { get; set; }
        public bool      /**/ c71                         /**/ { get; set; }
        public bool      /**/ c81                         /**/ { get; set; }
        public bool      /**/ c91                         /**/ { get; set; }
        public bool      /**/ c92                         /**/ { get; set; }
        public bool      /**/ c101                        /**/ { get; set; }
        public bool      /**/ c111                        /**/ { get; set; }
        public bool      /**/ c121                        /**/ { get; set; }
        public bool      /**/ c122                        /**/ { get; set; }
        public bool      /**/ c123                        /**/ { get; set; }
        public bool      /**/ cek                         /**/ { get; set; }
        public bool      /**/ cek11                       /**/ { get; set; }
        public bool      /**/ cek12                       /**/ { get; set; }
        public bool      /**/ cek13                       /**/ { get; set; }
        public bool      /**/ cek21                       /**/ { get; set; }
        public bool      /**/ cek22                       /**/ { get; set; }
        public bool      /**/ cek31                       /**/ { get; set; }
        public bool      /**/ cek41                       /**/ { get; set; }
        public bool      /**/ cek42                       /**/ { get; set; }
        public bool      /**/ but                         /**/ { get; set; }
        public bool      /**/ kasa                        /**/ { get; set; }
        public bool      /**/ k11                         /**/ { get; set; }
        public bool      /**/ k12                         /**/ { get; set; }
        public bool      /**/ k13                         /**/ { get; set; }
        public bool      /**/ k21                         /**/ { get; set; }
        public bool      /**/ k31                         /**/ { get; set; }
        public bool      /**/ k41                         /**/ { get; set; }
        public bool      /**/ k42                         /**/ { get; set; }
        public bool      /**/ k43                         /**/ { get; set; }
        public bool      /**/ k51                         /**/ { get; set; }
        public bool      /**/ muh                         /**/ { get; set; }
        public bool      /**/ m11                         /**/ { get; set; }
        public bool      /**/ m12                         /**/ { get; set; }
        public bool      /**/ m13                         /**/ { get; set; }
        public bool      /**/ m21                         /**/ { get; set; }
        public bool      /**/ m22                         /**/ { get; set; }
        public bool      /**/ m23                         /**/ { get; set; }
        public bool      /**/ m31                         /**/ { get; set; }
        public bool      /**/ m41                         /**/ { get; set; }
        public bool      /**/ m42                         /**/ { get; set; }
        public bool      /**/ m43                         /**/ { get; set; }
        public bool      /**/ m51                         /**/ { get; set; }
        public bool      /**/ m52                         /**/ { get; set; }
        public bool      /**/ m61                         /**/ { get; set; }
        public bool      /**/ m62                         /**/ { get; set; }
        public bool      /**/ m71                         /**/ { get; set; }
        public bool      /**/ m72                         /**/ { get; set; }
        public bool      /**/ m81                         /**/ { get; set; }
        public bool      /**/ m82                         /**/ { get; set; }
        public bool      /**/ m91                         /**/ { get; set; }
        public bool      /**/ m101                        /**/ { get; set; }
        public bool      /**/ m111                        /**/ { get; set; }
        public bool      /**/ m121                        /**/ { get; set; }
        public bool      /**/ m131                        /**/ { get; set; }
        public bool      /**/ m141                        /**/ { get; set; }
        public bool      /**/ m151                        /**/ { get; set; }
        public bool      /**/ m161                        /**/ { get; set; }
        public bool      /**/ m162                        /**/ { get; set; }
        public bool      /**/ m171                        /**/ { get; set; }
        public bool      /**/ m181                        /**/ { get; set; }
        public bool      /**/ m191                        /**/ { get; set; }
        public bool      /**/ m201                        /**/ { get; set; }
        public bool      /**/ m211                        /**/ { get; set; }
        public bool      /**/ m221                        /**/ { get; set; }
        public bool      /**/ m231                        /**/ { get; set; }
        public bool      /**/ m241                        /**/ { get; set; }
        public bool      /**/ m242                        /**/ { get; set; }
        public bool      /**/ m243                        /**/ { get; set; }
        public bool      /**/ m251                        /**/ { get; set; }
        public bool      /**/ par                         /**/ { get; set; }
        public bool      /**/ p11                         /**/ { get; set; }
        public bool      /**/ p12                         /**/ { get; set; }
        public bool      /**/ p13                         /**/ { get; set; }
        public bool      /**/ p21                         /**/ { get; set; }
        public bool      /**/ p22                         /**/ { get; set; }
        public bool      /**/ p23                         /**/ { get; set; }
        public bool      /**/ p31                         /**/ { get; set; }
        public bool      /**/ p41                         /**/ { get; set; }
        public bool      /**/ p42                         /**/ { get; set; }
        public bool      /**/ p43                         /**/ { get; set; }
        public bool      /**/ p51                         /**/ { get; set; }
        public bool      /**/ p52                         /**/ { get; set; }
        public bool      /**/ p53                         /**/ { get; set; }
        public bool      /**/ p61                         /**/ { get; set; }
        public bool      /**/ p62                         /**/ { get; set; }
        public bool      /**/ p63                         /**/ { get; set; }
        public bool      /**/ stk                         /**/ { get; set; }
        public bool      /**/ s11                         /**/ { get; set; }
        public bool      /**/ s12                         /**/ { get; set; }
        public bool      /**/ s13                         /**/ { get; set; }
        public bool      /**/ s21                         /**/ { get; set; }
        public bool      /**/ s22                         /**/ { get; set; }
        public bool      /**/ s23                         /**/ { get; set; }
        public bool      /**/ s31                         /**/ { get; set; }
        public bool      /**/ s32                         /**/ { get; set; }
        public bool      /**/ s33                         /**/ { get; set; }
        public bool      /**/ s41                         /**/ { get; set; }
        public bool      /**/ s42                         /**/ { get; set; }
        public bool      /**/ s43                         /**/ { get; set; }
        public bool      /**/ s51                         /**/ { get; set; }
        public bool      /**/ s52                         /**/ { get; set; }
        public bool      /**/ s53                         /**/ { get; set; }
        public bool      /**/ s61                         /**/ { get; set; }
        public bool      /**/ s62                         /**/ { get; set; }
        public bool      /**/ s63                         /**/ { get; set; }
        public bool      /**/ s71                         /**/ { get; set; }
        public bool      /**/ s72                         /**/ { get; set; }
        public bool      /**/ s73                         /**/ { get; set; }
        public bool      /**/ s81                         /**/ { get; set; }
        public bool      /**/ s82                         /**/ { get; set; }
        public bool      /**/ s83                         /**/ { get; set; }
        public bool      /**/ s91                         /**/ { get; set; }
        public bool      /**/ s92                         /**/ { get; set; }
        public bool      /**/ s93                         /**/ { get; set; }
        public bool      /**/ s101                        /**/ { get; set; }
        public bool      /**/ s102                        /**/ { get; set; }
        public bool      /**/ s103                        /**/ { get; set; }
        public bool      /**/ s111                        /**/ { get; set; }
        public bool      /**/ s121                        /**/ { get; set; }
        public bool      /**/ s122                        /**/ { get; set; }
        public bool      /**/ s131                        /**/ { get; set; }
        public bool      /**/ s132                        /**/ { get; set; }
        public bool      /**/ s141                        /**/ { get; set; }
        public bool      /**/ s151                        /**/ { get; set; }
        public bool      /**/ s152                        /**/ { get; set; }
        public bool      /**/ s153                        /**/ { get; set; }
        public bool      /**/ s161                        /**/ { get; set; }
        public bool      /**/ s171                        /**/ { get; set; }
        public bool      /**/ s181                        /**/ { get; set; }
        public bool      /**/ s182                        /**/ { get; set; }
        public bool      /**/ s183                        /**/ { get; set; }
        public bool      /**/ s191                        /**/ { get; set; }
        public bool      /**/ s192                        /**/ { get; set; }
        public bool      /**/ s193                        /**/ { get; set; }
        public bool      /**/ sat                         /**/ { get; set; }
        public bool      /**/ sat11                       /**/ { get; set; }
        public bool      /**/ sat12                       /**/ { get; set; }
        public bool      /**/ sat13                       /**/ { get; set; }
        public bool      /**/ sat21                       /**/ { get; set; }
        public bool      /**/ sat22                       /**/ { get; set; }
        public bool      /**/ sat31                       /**/ { get; set; }
        public bool      /**/ sat32                       /**/ { get; set; }
        public bool      /**/ sat33                       /**/ { get; set; }
        public bool      /**/ sat41                       /**/ { get; set; }
        public bool      /**/ sat42                       /**/ { get; set; }
        public bool      /**/ sat43                       /**/ { get; set; }
        public bool      /**/ sat51                       /**/ { get; set; }
        public bool      /**/ sat52                       /**/ { get; set; }
        public bool      /**/ sat53                       /**/ { get; set; }
        public bool      /**/ sat61                       /**/ { get; set; }
        public bool      /**/ sat71                       /**/ { get; set; }
        public bool      /**/ sat72                       /**/ { get; set; }
        public bool      /**/ sat73                       /**/ { get; set; }
        public bool      /**/ dem                         /**/ { get; set; }
        public bool      /**/ User_Islet                  /**/ { get; set; }
        public bool      /**/ s154                        /**/ { get; set; }
        public bool      /**/ s201                        /**/ { get; set; }
        public bool      /**/ s999                        /**/ { get; set; }
        public bool      /**/ User_Onay1                  /**/ { get; set; }
        public bool      /**/ User_Onay2                  /**/ { get; set; }
        public bool      /**/ User_Onay3                  /**/ { get; set; }
        public bool      /**/ User_Onay4                  /**/ { get; set; }
        public bool      /**/ User_Onay5                  /**/ { get; set; }
        public bool      /**/ User_Onay6                  /**/ { get; set; }
        public bool      /**/ sat81                       /**/ { get; set; }
        public bool      /**/ sat91                       /**/ { get; set; }
        public bool      /**/ sat101                      /**/ { get; set; }
        public bool      /**/ sat102                      /**/ { get; set; }
        public bool      /**/ sat103                      /**/ { get; set; }
        public bool      /**/ Hesap_Onay                  /**/ { get; set; }
        public bool      /**/ c112                        /**/ { get; set; }
        public bool      /**/ Info_Kaydet                 /**/ { get; set; }
        public bool      /**/ Info_Sil                    /**/ { get; set; }
        public bool      /**/ Pdf_Sil                     /**/ { get; set; }
        public bool      /**/ Hesap_Kilit                 /**/ { get; set; }
        public bool      /**/ s44                         /**/ { get; set; }
        public bool      /**/ EDefter                     /**/ { get; set; }
        public bool      /**/ sat_talepsaat               /**/ { get; set; }
        public int       /**/ User_Sat_Min                /**/ { get; set; }
        public bool      /**/ Stok_Kilit                  /**/ { get; set; }
        public bool      /**/ Mail_Gitsin                 /**/ { get; set; }
        public string    /**/ Mail_Adres                  /**/ { get; set; }
        public bool      /**/ Opera_Kilit                 /**/ { get; set; }
        public bool      /**/ User_SatOnaySifirla         /**/ { get; set; }
        public bool      /**/ User_BarkodSistemi          /**/ { get; set; }
        public bool      /**/ User_BarkodSistemiMenu      /**/ { get; set; }
        public bool      /**/ User_StokBarkodTipi         /**/ { get; set; }
        public bool      /**/ User_SatBilgiPenceresi      /**/ { get; set; }
        public bool      /**/ m252                        /**/ { get; set; }
        public bool      /**/ User_TekSecsube             /**/ { get; set; }
        public string    /**/ User_SecSube                /**/ { get; set; }
        public bool      /**/ User_Senaryo                /**/ { get; set; }
        public string    /**/ User_SenaryoHesap           /**/ { get; set; }
        public bool      /**/ User_TekdepRapor            /**/ { get; set; }
        public string    /**/ User_DepRapor               /**/ { get; set; }
        public bool      /**/ User_BarkodSilme            /**/ { get; set; }
        public bool      /**/ User_KonsolideMenu          /**/ { get; set; }
        public bool      /**/ User_Ftp                    /**/ { get; set; }
        public bool      /**/ User_MalKabulLink           /**/ { get; set; }
        public bool      /**/ User_MalKabulListe          /**/ { get; set; }
        public bool      /**/ User_MalKabulHavuz          /**/ { get; set; }
        public bool      /**/ User_MalKabulForm           /**/ { get; set; }
        public bool      /**/ m253                        /**/ { get; set; }
    }
}